services:
  novactive-ai-manager:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: novactive-ai-manager
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "8000:8000"
